### ISSUE TITLE
I got the msg "Error running plugin hook transform for preserve-directives, expected a function hook."

### ISSUE THREAD

**Issue by deli-ght** [huozhi/rollup-preserve-directives#23]
I got the error msg like this. Is there any solution for this?

<img width="395" alt="image" src="https://github.com/huozhi/rollup-preserve-directives/assets/77158595/976f300c-1c38-4b47-98e4-9e271a985867">

**Comment by huozhi** [comment]
Can you share a reproduction that how are you testing with it right now?

**Comment by deli-ght** [comment]
@huozhi Thanks for reply.

I try to make a design system with react , vanilla-extract and rollup
so I config the `rollup.config.js` like this.

```
import { vanillaExtractPlugin } from "@vanilla-extract/rollup-plugin";
import nodeResolve from "@rollup/plugin-node-resolve";
import commonjs from "@rollup/plugin-commonjs";
import babel from "@rollup/plugin-babel";
import typescript from "@rollup/plugin-typescript";
import preserveDirectives from "rollup-preserve-directives";

export default {
  input: "src/index.ts",
  output: {
    file: "dist/index.js",
    format: "esm",
  },
  plugins: [
    vanillaExtractPlugin(),
    preserveDirectives(),
    nodeResolve({
      extensions: [".js", ".jsx", ".ts", ".tsx"],
    }),
    babel({
      babelHelpers: "bundled",
      presets: ["@babel/preset-react"],
      extensions: [".js", ".jsx", ".ts", ".tsx"],
    }),
    commonjs(),
    typescript({
      tsconfig: "tsconfig.json",
      declaration: true,
      declarationDir: "dist",
      outputToFilesystem: true,
    }),
  ],
  external: ["react", "react-dom"],
};
```

and run `rollup -c` the result was that

**Comment by huozhi** [comment]
Maybe it's transformed to sth different? Can you log it out what is the plugin we imported there.

Another way is to try named exports
```
import { preserveDirective } from "rollup-preserve-directives"
```

**Comment by deli-ght** [comment]
> Maybe it's transformed to sth different? Can you log it out what is the plugin we imported there.
> 
> Another way is to try named exports
> 
> ```
> import { preserveDirective } from "rollup-preserve-directives"
> ```

Could you explain more detail for `Can you log it out what is the plugin we imported there.`?
you mean this maybe..?
<img width="371" alt="image" src="https://github.com/huozhi/rollup-preserve-directives/assets/77158595/dfde7ed8-4973-4aaf-86b3-a8e91db28530">

or this? (src/index.ts)
<img width="511" alt="image" src="https://github.com/huozhi/rollup-preserve-directives/assets/77158595/89261ce7-a5ca-4a9d-b162-e490360ce4be">

and sadly, it doesn't work neither...
```
import { preserveDirective } from "rollup-preserve-directives"
```

**Comment by SukkaW** [comment]
@huozhi I suspect that our plugin is not compatible with rollup 2.73.0 (which @deli-ght is using). We might test that.
